/-
  TranslationOrchestrator.lean
  Parallel orchestrator for batch code translation to Meirei IR.

  Each file is translated independently via its own FlowProviderAdapter
  (and thus its own claude subprocess) using IO.asTask for concurrency.
  Tree-sitter pre-parsing provides structured input; the LLM agent
  handles all type understanding and Meirei IR mapping.
-/

import PredictableAgents.Provider.ClaudeCLI
import PredictableCore.Shared.Index
import PredictableVerification.Translation.TranslationTypes
import PredictableVerification.Translation.PromptBuilder
import PredictableVerification.Translation.TranslationAgent

namespace PredictableVerification.Translation

open Agents.Provider Agents.Provider.ClaudeCLI Agents.Parameters
open PredictableCore.Shared

/-- Result of translating a single file. -/
structure TranslateFileResult where
  sourcePath : System.FilePath
  outputPath : System.FilePath
  success : Bool
  confidence : Option String
  error : Option String
  elapsedMs : Nat
  approxCount : Nat
  deriving Lean.ToJson

/-- Aggregated result of the translation orchestration. -/
structure TranslateOrchestrationResult where
  results : Array TranslateFileResult
  deriving Lean.ToJson

private def formatDuration (ms : Nat) : String :=
  if ms < 1000 then s!"{ms}ms"
  else if ms < 60000 then
    let secs := ms / 1000
    let frac := (ms % 1000) / 100
    s!"{secs}.{frac}s"
  else
    let mins := ms / 60000
    let secs := (ms % 60000) / 1000
    s!"{mins}m{secs}s"

private def baseName (path : System.FilePath) : String :=
  let filename := path.fileName.getD "unknown"
  match filename.splitOn "." with
  | name :: _ => name
  | [] => filename

private def languageFromPath (path : System.FilePath) : SourceLanguage :=
  match path.extension with
  | some "kt" => .kotlin
  | _ => .java

private def generateHeader
    (sourcePath : System.FilePath)
    (lang : SourceLanguage)
    (confidence : ConfidenceLevel)
    : String :=
  s!"/-\n  Auto-generated by: predictable translate\n  Source: {sourcePath}\n" ++
  s!"  Language: {lang}\n  Confidence: {confidence}\n-/\n\n"

-- Translate a single file using TranslationAgent via FlowProviderAdapter.
-- Runs in IO so it can be spawned as an independent IO.asTask.
private def translateFileIO
    (agent : TranslationAgent)
    (sourcePath : System.FilePath)
    (outputDir : System.FilePath)
    (verbose : Bool := false)
    : IO TranslateFileResult := do
  let name := baseName sourcePath
  let startTime ← IO.monoMsNow
  let sourceCode ← IO.FS.readFile sourcePath
  let lang := languageFromPath sourcePath
  let request : TranslationRequest :=
    { sourceCode, language := lang, context := none
      methodName := some name }
  let outputPath := outputDir / (name ++ ".lean")
  if verbose then
    IO.eprintln s!"      Sending to LLM..."
  match ← agent.translateWithRetry request with
  | .ok result =>
    let header := generateHeader sourcePath lang result.confidence
    IO.FS.writeFile outputPath (header ++ result.meireiCode)
    let elapsed := (← IO.monoMsNow) - startTime
    let approxCount := result.approximations.length
    if verbose then
      for approx in result.approximations do
        let loc := approx.location.getD ""
        IO.eprintln s!"        • {approx.type} [{approx.severity}] {loc}: {approx.description}"
      IO.eprintln s!"      --- Meirei IR ---"
      IO.eprintln result.meireiCode
      IO.eprintln s!"      --- end ---"
    return { sourcePath, outputPath, success := true
             confidence := some (toString result.confidence), error := none
             elapsedMs := elapsed, approxCount }
  | .error e =>
    let elapsed := (← IO.monoMsNow) - startTime
    return { sourcePath, outputPath, success := false
             confidence := none, error := some (toString e)
             elapsedMs := elapsed, approxCount := 0 }

/-- Split an array into chunks of at most the given size. -/
def chunkArray (arr : Array α) (size : Nat) : Array (Array α) :=
  if size == 0 then #[arr]
  else Id.run do
    let mut chunks : Array (Array α) := #[]
    let mut i := 0
    while i < arr.size do
      let endIdx := min (i + size) arr.size
      let mut chunk : Array α := #[]
      for j in [i:endIdx] do
        if h : j < arr.size then
          chunk := chunk.push arr[j]
      chunks := chunks.push chunk
      i := i + size
    return chunks

private def spinnerFrames : Array String := #["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"]

-- Background spinner that animates [ ] entries for in-flight files.
-- Returns an IO.Ref Bool that the caller sets to true to stop.
private def startSpinner
    (total : Nat)
    (completedRef : IO.Ref (Array Bool))
    (names : Array String)
    : IO (IO.Ref Bool) := do
  let stopRef ← IO.mkRef false
  let _ ← IO.asTask (prio := .default) do
    let mut frame := 0
    repeat do
      if ← stopRef.get then break
      let completed ← completedRef.get
      let ch := spinnerFrames[frame % spinnerFrames.size]!
      for i in [:total] do
        if h : i < completed.size then
          unless completed[i] do
            let linesUp := total - i
            let name := if h2 : i < names.size then names[i] else "?"
            IO.eprint s!"\x1b[{linesUp}A\r  - [{ch}] {name}\x1b[K\x1b[{linesUp}B\r"
      frame := frame + 1
      IO.sleep 80
  pure stopRef

-- Translate files in parallel. Each file gets its own TranslationAgent
-- (and thus its own claude subprocess) spawned via IO.asTask.
-- Concurrency controls how many files are in-flight simultaneously.
private def translateBatchParallel
    (misses : Array System.FilePath)
    (outputDir : System.FilePath)
    (verbose : Bool)
    (concurrency : Nat)
    : IO (Array TranslateFileResult) := do
  let total := misses.size
  let names : Array String := misses.map baseName
  for i in [:total] do
    if h : i < names.size then
      IO.eprintln s!"  - [ ] {names[i]}"
  let completedRef ← IO.mkRef ((Array.range total).map fun _ => false)
  let stopSpinner ← startSpinner total completedRef names
  let chunks := chunkArray misses concurrency
  let mut allResults : Array TranslateFileResult := #[]
  let mut globalIdx := 0
  for chunk in chunks do
    let mut tasks : Array (Nat × Task (Except IO.Error TranslateFileResult)) := #[]
    for file in chunk do
      let idx := globalIdx
      globalIdx := globalIdx + 1
      let agentConfig : TranslationAgentConfig :=
        { TranslationAgentConfig.default with
          verbose := verbose }
      let agent := TranslationAgent.create agentConfig
      let task ← IO.asTask (prio := .dedicated) do
        translateFileIO agent file outputDir verbose
      tasks := tasks.push (idx, task)
    for (taskIdx, task) in tasks do
      let errResult : TranslateFileResult :=
          { sourcePath := ⟨"unknown"⟩, outputPath := ⟨"unknown"⟩
            success := false, confidence := none, error := none
            elapsedMs := 0, approxCount := 0 }
      let result := match ← IO.wait task with
        | Except.ok r => r
        | Except.error e => { errResult with error := some (toString e) }
      allResults := allResults.push result
      completedRef.modify fun arr =>
        if h : taskIdx < arr.size then arr.set taskIdx true else arr
      let linesUp := total - taskIdx
      let name := baseName result.sourcePath
      let dur := formatDuration result.elapsedMs
      if result.success then
        IO.eprint s!"\x1b[{linesUp}A\r  - [✓] {name} ({result.confidence.getD "?"}, {dur})\x1b[K\x1b[{linesUp}B\r"
      else
        let err := result.error.getD "unknown"
        IO.eprint s!"\x1b[{linesUp}A\r  - [✗] {name} (failed: {err})\x1b[K\x1b[{linesUp}B\r"
  stopSpinner.set true
  return allResults


/-- Parallel batch translation orchestrator.
    All files are translated concurrently via independent FlowProviderAdapter
    instances (each spawning its own claude subprocess via IO.asTask). -/
def orchestrateTranslation
    (files : Array System.FilePath)
    (outputDir : System.FilePath)
    (verbose : Bool := false)
    (concurrency : Nat := 1)
    : PredictableCodeProgram TranslateOrchestrationResult := do
  if files.isEmpty then
    return { results := #[] }

  let effectiveConcurrency := if concurrency > 0 then concurrency else files.size
  if verbose then
    Program.logDebug s!"  Concurrency: {effectiveConcurrency}"

  let results ←
    translateBatchParallel
      files outputDir verbose effectiveConcurrency

  return { results }

end PredictableVerification.Translation
