/-
  TranslationOrchestrator.lean
  Reactive orchestrator for batch code translation to Meirei IR.

  Translates files sequentially using a single agent flow, matching the
  schemas inference orchestrator pattern: one FlowProviderAdapter session
  handles all files via successive user messages.
-/

import PredictableAgents.Provider.ClaudeCLI
import PredictableCore.Shared.Index
import PredictableVerification.Translation.TranslationTypes
import PredictableVerification.Translation.PromptBuilder
import Flow.ReactiveProgram
import Flow.Index

namespace PredictableVerification.Translation

open Agents.Provider Agents.Provider.ClaudeCLI Agents.Parameters
open Agents.Error
open PredictableCore.Shared
open Flow.Core

/-- Result of translating a single file in the reactive pipeline. -/
structure TranslateFileResult where
  sourcePath : System.FilePath
  outputPath : System.FilePath
  success : Bool
  -- Stored as a string because ConfidenceLevel has no ToJson instance.
  confidence : Option String
  error : Option String
  deriving Lean.ToJson

/-- Aggregated result of the reactive translation orchestration. -/
structure TranslateOrchestrationResult where
  results : Array TranslateFileResult
  deriving Lean.ToJson

-- Events for the reactive translation pipeline.
-- processNext reads the current file and sends it to the agent.
-- responseReceived carries the raw LLM output; handleResponseReceived uses
-- state (current index) to build the per-file result and write the output file.
-- fileTranslated carries the processed result and drives loop advancement.
private inductive TranslateEvent where
  | processNext
  | responseReceived : LLMTranslationResponse → TranslateEvent
  | fileTranslated : TranslateFileResult → TranslateEvent
  | completed
  | failed : String → TranslateEvent

-- Reactive loop state.
-- `result` is populated only when all files have been processed, signalling closure.
private structure TranslateLoopState where
  files : Array System.FilePath
  outputDir : System.FilePath
  verbose : Bool
  results : Array TranslateFileResult
  result : Option TranslateOrchestrationResult

-- Files are processed one at a time via a single-source flow, so merge is never called.
-- BEq compares result counts only — sufficient for the sequential single-source case.
private instance : BEq TranslateLoopState where
  beq a b :=
    a.files.size == b.files.size &&
    a.results.size == b.results.size &&
    a.result.isSome == b.result.isSome

private instance : Flows.MergeableState TranslateLoopState where
  merge _ new _ := new
  withEmptyAppendable s := s

-- `fileTranslated` pushes the per-file result; `completed` sets the terminal result.
-- All other events are no-ops in the pure state transition.
private def translateUpdate
    (state : TranslateLoopState)
    (event : TranslateEvent)
    : TranslateLoopState :=
  match event with
  | .fileTranslated result => { state with results := state.results.push result }
  | .completed => { state with result := some { results := state.results } }
  | _ => state

-- Converts agent flow events to pipeline events.
-- The LLM response is passed through verbatim so handleResponseReceived can
-- use state (current file index) to build the per-file result.
private def translateAgentEvent
    : Except AgentError (AgentRequestEvent LLMTranslationResponse)
    → Option (Except BaseError TranslateEvent)
  | .ok (.chunk llmResp) => some (.ok (.responseReceived llmResp))
  | .error e => some (.ok (.failed (toString e)))
  | _ => none

private def baseName (path : System.FilePath) : String :=
  let filename := path.fileName.getD "unknown"
  match filename.splitOn "." with
  | name :: _ => name
  | [] => filename

private def languageFromPath (path : System.FilePath) : SourceLanguage :=
  match path.extension with
  | some "kt" => .kotlin
  | _ => .java

private def generateHeader
    (sourcePath : System.FilePath)
    (lang : SourceLanguage)
    (confidence : ConfidenceLevel)
    : String :=
  s!"/-\n  Auto-generated by: predictable translate\n  Source: {sourcePath}\n" ++
  s!"  Language: {lang}\n  Confidence: {confidence}\n-/\n\n"

-- Sends the current file's source to the agent flow.
-- Current file index = state.results.size (number of files already processed).
private def handleProcessNext
    (agentFlow : AgentRequestFlow LLMTranslationResponse)
    (accessor : FlowAccessor BaseError TranslateEvent)
    (state : TranslateLoopState)
    : ReaderT PredictableConfig (ExceptT BaseError IO) Unit := do
  let idx := state.results.size
  if h : idx < state.files.size then
    let sourcePath := state.files[idx]
    let total := state.files.size
    SideEffect.logInfo s!"  [{idx + 1}/{total}] {baseName sourcePath}"
    let sourceCode ← IO.FS.readFile sourcePath
    let lang := languageFromPath sourcePath
    let request : TranslationRequest :=
      { sourceCode, language := lang, context := none, methodName := some (baseName sourcePath) }
    agentFlow.emit (.message (.user request.toXML))
  else
    accessor.emit .completed

-- Processes the LLM response for the current file: writes the output file and emits
-- fileTranslated so `update` can advance state.results.
private def handleResponseReceived
    (resp : LLMTranslationResponse)
    (accessor : FlowAccessor BaseError TranslateEvent)
    (state : TranslateLoopState)
    : ReaderT PredictableConfig (ExceptT BaseError IO) Unit := do
  let idx := state.results.size
  if h : idx < state.files.size then
    let sourcePath := state.files[idx]
    let lang := languageFromPath sourcePath
    let outputPath := state.outputDir / (baseName sourcePath ++ ".lean")
    let translationResult := resp.toTranslationResult TokenUsage.empty "claude-sonnet-4-20250514" none
    let header := generateHeader sourcePath lang translationResult.confidence
    let content := header ++ translationResult.meireiCode
    IO.FS.writeFile outputPath content
    if state.verbose then
      SideEffect.logInfo s!"      Confidence: {translationResult.confidence}"
    accessor.emit <| .fileTranslated
      { sourcePath, outputPath, success := true
        confidence := some (toString translationResult.confidence), error := none }
  else
    accessor.emit .completed

private def translateSideEffect
    (agentFlow : AgentRequestFlow LLMTranslationResponse)
    (state : TranslateLoopState)
    (event : TranslateEvent)
    (accessor : FlowAccessor BaseError TranslateEvent)
    : ReaderT PredictableConfig (ExceptT BaseError IO) Unit :=
  match event with
  | .processNext => handleProcessNext agentFlow accessor state
  | .responseReceived resp => handleResponseReceived resp accessor state
  -- state.results is already updated by `update` for fileTranslated; decide whether to continue.
  | .fileTranslated _ =>
    if state.results.size >= state.files.size then
      accessor.emit .completed
    else
      accessor.emit .processNext
  | .completed => accessor.close
  | .failed msg => do
    let idx := state.results.size
    SideEffect.logWarn s!"Translation failed for file {idx + 1}: {msg}"
    if h : idx < state.files.size then
      let sourcePath := state.files[idx]
      let outputPath := state.outputDir / (baseName sourcePath ++ ".lean")
      -- Emit the error result so `update` advances state.results and the loop continues.
      accessor.emit <| .fileTranslated
        { sourcePath, outputPath, success := false, confidence := none, error := some msg }
    else
      accessor.emit .completed

/-- Reactive batch translation orchestrator.
    Translates all files sequentially via a single agent flow,
    writing output to outputDir as each file completes. -/
def orchestrateTranslation
    (files : Array System.FilePath)
    (outputDir : System.FilePath)
    (verbose : Bool := false)
    : PredictableCodeProgram TranslateOrchestrationResult := do
  if files.isEmpty then
    return { results := #[] }

  let pConfig ← PredictableProgram.ask
  let agentConfig : AgentRequestConfig :=
    { config := ProviderConfig.default
      params := RequestParameters.default
      logTargets := pConfig.logTargets
      colorEnabled := pConfig.colorEnabled
      basePath := pConfig.basePath
      skipPermissionsRef := none
      allowedToolsRef := none }
  let adapter := createFlowAdapter agentConfig
  let systemPrompt := buildStructuredPrompt .full allExamples
  let agentFlow ← liftIOExcept <|
    adapter.startStructured (α := LLMTranslationResponse) systemPrompt

  let initialState : TranslateLoopState :=
    { files, outputDir, verbose, results := #[], result := none }

  let finalState ← ReactiveProgram.launchReactiveProgram
    { initialState
      update := translateUpdate
      sideEffect := translateSideEffect agentFlow
      firstMessage := TranslateEvent.processNext
      onUpdated := fun _ => pure ()
      sources := #[IOSubscribable.mapped agentFlow.underlying translateAgentEvent]
      onClose := #[agentFlow.close] }

  finalState
  |>.bind (·.result)
  |>.getDM <| Except.error <|
    BaseError.llmFailure
    "Translation reactive loop terminated without producing a result"

end PredictableVerification.Translation
